### ISSUE TITLE
testin to do list review

### ISSUE THREAD

**Issue by mohamed20163858** [DebbyMiressa/To-Do-List#9]
hello, Debby your work is amazing you really did a great job writing your test cases however I think there is a little bugs
1) in your final test case about testing clear all completed we suggest at least you need to create 3  items 1 not completed and 2 are checked completed to test your clear() method in the code below to see if it can remove more than 2 items or not.  what do you think?
```
it('Test 3: test clear all completed', () => {

    //Assign

    // Act => simulate clicking the clear button to delete all checked tasks
    ts.clear();
    simulateBtnClick();

    //Assert => expected - count = 0
    //          recieved - count of checkbox which are checked
    const checkboxes = document.querySelectorAll('.checker');
    let count = 0;
    checkboxes.forEach((checkbox) => {
      if (checkbox.checked === true) {
        count += 1;
      }
    });
    expect(count).toBe(0);
  })
``` 
thanks a lot and Great Job!

**Comment by DebbyMiressa** [comment]
Thank you for the comment! I will make sure to integrate the changes suggested! The test should be effective!
